server:
  port: 10000
spring:
  application:
    name: config
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: Service-Config
    config:
      server:
        git:
          uri: http://jn.github/yangguoqing/cloudconfig.git
          username: yangguoqing
          password: yang!Q2w
          searchPaths: '{profile}'
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: cloud
    password: cloud
management:
  endpoints:
    web:
      exposure:
        include: "*"

